### ISSUE TITLE
[Feature suggestion] Let CodeReader fully support landscape orientation

### ISSUE THREAD

**Issue by Olf0** [monich/sailfish-barcode#1]
#### Background
* CodeReader is almost there: It is (was?) working well in landscape orientation, but exposes some minor usability issues.
* I am using the Patches "[Free Rotate for Phone](https://openrepos.net/content/alina/patch-allow-any-orientation-except-inverted-portrait-sailfishos-apps)", respectively "[Allow any rotation](https://coderus.openrepos.net/pm2/project/uirotate-free)".

#### Missing pieces
* In the main screen, the preview window (both, content and frame / window orientation) ought to be rotated by 90° to the left, when in landscape orientation, by 90° to the right, when in inverted landscape orientation and by 180°, when in inverted portrait orientation.
Without this measure (i.e. currently), aiming at a barcode in landscape orientation provides a clumsy experience, because movements of the hand and device are translated into orthogonal movements of the view within the preview window.
* The settings screen must be made scrollable.

#### Notes
* The detection rate of CodeReader 1.0.0 in landscape orientation seems to be 0 (tried a couple of Barcodes on products), while it works like a charm in portrait orientation.  CodeReader versions up to (and including) 0.7.13 did successful scans in landscape orientation.
* It would be a useful feature (additionally to above suggestion for adapting the default orientation of the preview window) to be able to manually rotate the **frame** of the preview window (i.e. its orientation, but not its content, in contrast to above suggestion) by 90°, regardless of the current orientation (e.g. by tapping on the preview window or via a pulley entry), so one does not have to rotate the object with the barcode on (which is impractical or even infeasible sometimes) to make it fit in the preview window.
A likely easier way to accomplish this would be to use a square preview window, as most QR- and Barcode apps do.

@monich, thank you so much for maintaining this extremely useful app, providing functionality the SailfishOS (native) software ecosystem would be simply lacking without it.

**Comment by Olf0** [comment]
The settings page in v1.0.10 is looking nice in portrait and landscape orientation.  Thanks!

WRT rotation:
* It is good to know, that the the app is trying to detect the code in 0° and 90°, already.
That explains well, why it is detecting codes, although the picture (at least the preview) is rotated.
* But the point is, for the user, the preview picture is out-of-sync (by multiples if 90°) with reality!
I.e. the preview picture is rotated by 90° compared to what is visible behind the phone in landscape orientation, by 180° when in inverted portrait orientation and by 270° when in inverted landscape orientation.  That is the reason, why I suggested:
> In the main screen, the preview window (both, content and frame / window orientation) ought to be rotated by 90° to the left, when in landscape orientation, by 90° to the right, when in inverted landscape orientation and by 180°, when in inverted portrait orientation.
Without this measure (i.e. currently), aiming at a barcode in landscape orientation provides a clumsy experience, because movements of the hand and device are translated into orthogonal movements of the view within the preview window.

**Comment by develroo** [comment]
If I might just point out that the Gemini PDA is a primary landscape devices. As it stands CodeReader will not work in that orientation because the scan now button falls off the bottom of the screen and you cannot scan. Reorientate it portrait and it works fine. But Landscape is the normal orientation. 

Thanks.

**Comment by Olf0** [comment]
@monich, I forgot to mention, that the detection in landscape is working fine (but, see below) and the detection rate has become really good (on par with barcode scanners for Android) and quick with the latest releases of CodeReader (tested with v1.0.11 from Jolla Store).  Thanks!

But unfortunately the redesigned viewfinder (with aspect ratio switch) has some flaws IMHO:
- Its aspect ratio switcher allows for switching between a vertically tall (as before, AFAICS) and a vertically extremely tall viewfinder.  The latter exacerbates the aforementioned issues in landscape orientation.
While I like the idea of the aspect ratio switcher, currently it does not alleviate this issue.   Offering a square viewfinder (i.e., with an aspect ratio of 1:1) instead of the extremely tall one would, though I do not believe that this is the best way to solve these issues in landscape orientation.
Side note: IMO the aspect ratio switcher should rather be in the settings, as supposedly one uses a specific aspect ratio on a specific device.  Furthermore this allows for a line of text (e.g. "Viewfinder aspect ratio"), describing its function.
- There is now a large gap between the zoom slider (with flashlight and aspect ratio switchers) and the "Scan" button.  This causes the "Scan" button to be that far offscreen, that it is outside of the scrollable range of this window (not only on the Gemini PDA, as @develroo described, also on other devices, e.g. Jolla 1) in landscape orientation.
- The viewfinder is vertically so large (no matter which of the aspect ratios is used), that one has to scroll to see the zoom slider with flashlight and aspect ratio switchers in landscape orientation.  Nice that scrolling works fine, but IMHO scrolling should not be necessary.

Hence my suggestions are:
- Please eliminate the large gap between the zoom slider (with flashlight and aspect ratio switchers) and the "Scan" button.
- Please let the viewfinder proper and its content rotate with the device by 0°, 90°, 180° and 270°.  If it does that, I think the currently offered aspect ratios are absolutely fine (and no square one should be introduced).

**Comment by monich** [comment]
Build 1.0.14 should fully support landscape. Just submitted it to the Jolla Store. Let me know if something is still missing.

**Comment by Olf0** [comment]
Nice, thanks!
This is looking good, I cannot think of other improvements WRT landscape support.

**Comment by Olf0** [comment]
Oh, the size of the viewfinder window differs on my "testing" Jolla 1 phone and my "production" Jolla 1.  I already wondered about the small size and not very wide aspect ratio on my "testing" Jolla 1, until I saw that it looks absolutely fine on my "production" Jolla 1 (Codereader was updated to v1.0.14 per the Jolla Store app on both Jolla 1s) and freshly installed on an Xperia X.
I assume the difference in the size and aspect ratio of the viewfinder window originates from a setting, which is not accessible at the GUI, anymore.  Is */home/nemo/.local/share/harbour-barcode/harbour-barcode/QML/OfflineStorage/Databases/<id>.sqlite* where the settings are stored?

Nevertheless, IMO it would be nice if Codereader resets this aspect ratio value (or whatever causes the differing viewfinder windows) upon updating it, now that its main window layout suits landscape orientation well.

* Codreader 1.0.14 on my "testing" Jolla 1 phone: 
* Codreader 1.0.14 on my "production" Jolla 1 phone: ![Screenshot_20190415_004](https://user-images.githubusercontent.com/16547876/56174484-fe055f00-5ff2-11e9-8d46-8c21c988e591.png)

* Codreader 1.0.14 on my Xperia X::

**Comment by monich** [comment]
Icon button on the right of the zoom slider switches the aspect ratio.

And no, aspect ratio is not in the database, settings are stored in dconf these days. The app copies old settings from the database to dconf when it finds them there, drops the "settings" table and keeps using dconf:

https://github.com/monich/sailfish-barcode/blob/master/src/Database.cpp#L233

You can read aspect ratio setting from dconf like this:
```
dconf read /apps/harbour-barcode/wide_mode
```

**Comment by Olf0** [comment]
Thanks for the prompt reply and the information WRT Codereader's settings.

As this turned out to be simply a usage issue ("the real issue most often sits in front of the device"), I am glad that I did not reopen this issue, yesterday.
So all is fine and working well for me with Codereader 1.0.14.
Cheers!

**Comment by develroo** [comment]
Yup can confirm it seems to work properly on the Gemini PDA now. Cool.

Thanks for that!

**Comment by Olf0** [comment]
@develroo , your comment made me trying to reproduce the behaviour of your Gemini:
* The aspect ratio switcher icon (to the right of the magnification slider) shows portrait orientation in your screenshot, while the device is in landscape orientation.
* The large vertical spacing, which [I criticised while testing Codereader v1.0.11](https://github.com/monich/sailfish-barcode/issues/1#issuecomment-406686701), is still there.

Checking the exact behaviour on one of my Jolla 1s:
* The aspect ratio switcher **always** shows landscape orientation, when the device is in landscape orientation, regardless of the settings in Codereader's *Settings -> Orientation {Primary, Portrait, Landscape, Dynamic}*!
* The same when the device is in portrait orientation: The aspect ratio switcher is **always** displayed in portrait orientation (regardless of the settings in Codereader's *Settings -> Orientation*).
* This seems to be exactly the opposite behaviour of your Gemini.

Hence I wonder, ...
* ... if you have Codereader 1.0.14 installed?<br />See *About Codereader* in its top pulley.
* ... if you have any "orientation Patch" (using Patchmanager) installed (e.g.  "[Free Rotate for Phone](https://openrepos.net/content/alina/patch-allow-any-orientation-except-inverted-portrait-sailfishos-apps)" or "[Allow any rotation](https://coderus.openrepos.net/pm2/project/uirotate-free)")?
* which of *Settings -> Display -> Orientation {Dynamic, Portrait, Landscape}* in SailfishOS' settings app is selected on your Gemini?
* if switching  *Settings -> Orientation {Primary, Portrait, Landscape, Dynamic}* in Codereader's settings makes any difference?

I hesitate to reopen this issue yet (i.e., without further analysis), because on my devices everything is working well now, even though not completely as expected (as Coderader's orientation setting does nothing).

**Comment by monich** [comment]
I guess `Screen.sizeCategory` on `Gemini is Screen.Large` or `Screen.ExtraLarge`:

https://github.com/monich/sailfish-barcode/blob/master/qml/pages/ScanPage.qml#L49

https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-sailfish-silica-screen.html/

**Comment by monich** [comment]
Perhaps I should use landscape layout for `Screen.Large` too...

**Comment by develroo** [comment]
That would make sense. The Screen Resolution for the Gemini is  2160×1080 @ 403 dpi

Functionally it works fine though.. just the viewport is teeny weeny.

**Comment by monich** [comment]
I'll consider using landscape layout on all devices regardless of their sizeCategory.
