### ISSUE TITLE
Remorse times slide doesn't work on the history page

### ISSUE THREAD

**Issue by ApostolosB** [monich/sailfish-barcode#13]
While the behavior changed in the latest update if you run Code reader with a previous version of SFOS the slide to dismiss gesture doesn't work. If you try to slide it it takes you back to the main page.

Since the slide will come back -according to joona- it needs to work correctly.

**Comment by monich** [comment]
That's strange, AFAICT I'm not doing anything fancy with remorse timers.

**Comment by monich** [comment]
I found a device running SFOS version with "slide to dismiss" and this gesture works nicely for me in the history view ¯\_(ツ)_/¯

**Comment by ApostolosB** [comment]
Since the slide to dismiss is coming back (most likely) we can wait a bit. When it lands i'll test again and close it myself if it doesn't happen.

**Comment by monich** [comment]
BTW, it never worked on the scan page (i.e. if you scan, click on the item below the camera area to open the detailed page, delete the new code from the pulley menu, that brings you back to the scan view and the item gets replaced with the remorse timer - slide to dismiss never worked there, not sure why)

**Comment by monich** [comment]
AFAICT slide to dismiss works nicely since Sailfish OS 3.4

**Comment by ApostolosB** [comment]
Closing. Seems to work fine.
