### ISSUE TITLE
The app doesn't install from the shop...

### ISSUE THREAD

**Issue by ApostolosB** [monich/sailfish-barcode#25]
...for tama devices. This is the log:

```
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::slotTransactionFinished(PackageKit::Transaction::Exit,
uint) PackageKit::Transaction::Exit(ExitSuccess) 12866
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::resolveInstalled(const QString&)
"harbour-barcode"
Jul 10 13:58:18 XperiaXZ2 PackageKit[20405]: resolve transaction
/633_accbcece from uid 100000 finished with success after 81ms
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::slotTransactionFinished(PackageKit::Transaction::Exit,
uint) PackageKit::Transaction::Exit(ExitSuccess) 81
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::resolve(const QString&)
"harbour-barcode"
Jul 10 13:58:18 XperiaXZ2 PackageKit[20405]: resolve transaction
/634_bdbbbdbc from uid 100000 finished with success after 1ms
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::slotTransactionFinished(PackageKit::Transaction::Exit,
uint) PackageKit::Transaction::Exit(ExitSuccess) 1
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::giveUpOrRetry(const QString&)
"could not find package harbour-barcode"
Jul 10 13:58:18 XperiaXZ2 [17585]: [D] unknown:0 - retry 1 / 3 in 10000 ms
Jul 10 13:58:19 XperiaXZ2 tracker-store[23296]: OK
Jul 10 13:58:28 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::resolve(const QString&)
"harbour-barcode"
Jul 10 13:58:28 XperiaXZ2 PackageKit[20405]: resolve transaction
/635_dcccdddc from uid 100000 finished with success after 1ms
Jul 10 13:58:28 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::slotTransactionFinished(PackageKit::Transaction::Exit,
uint) PackageKit::Transaction::Exit(ExitSuccess) 1
Jul 10 13:58:28 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::giveUpOrRetry(const QString&)
"could not find package harbour-barcode"
Jul 10 13:58:28 XperiaXZ2 [17585]: [D] unknown:0 - retry 2 / 3 in 10000 ms
Jul 10 13:58:31 XperiaXZ2 kernel: BUG: Bad rss-counter state
mm:ffffffc0b52baa00 idx:4 val:64
Jul 10 13:58:38 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::resolve(const QString&)
"harbour-barcode"
Jul 10 13:58:38 XperiaXZ2 PackageKit[20405]: resolve transaction
/636_deebcece from uid 100000 finished with success after 2ms
Jul 10 13:58:38 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::slotTransactionFinished(PackageKit::Transaction::Exit,
uint) PackageKit::Transaction::Exit(ExitSuccess) 2
Jul 10 13:58:38 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::giveUpOrRetry(const QString&)
"could not find package harbour-barcode"
Jul 10 13:58:38 XperiaXZ2 [17585]: [D] unknown:0 - retry 3 / 3 in 10000 ms
Jul 10 13:58:46 XperiaXZ2 healthd: battery l=42 v=3715 t=36.5 h=2 st=3
c=723 fc=3217000 chg=
Jul 10 13:58:48 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::resolve(const QString&)
"harbour-barcode"
Jul 10 13:58:48 XperiaXZ2 PackageKit[20405]: resolve transaction
/637_bbedadeb from uid 100000 finished with success after 1ms
Jul 10 13:58:48 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::slotTransactionFinished(PackageKit::Transaction::Exit,
uint) PackageKit::Transaction::Exit(ExitSuccess) 1
Jul 10 13:58:48 XperiaXZ2 [17585]: [D] unknown:0 - void
Package::InstallTransactionPkgKit::giveUpOrRetry(const QString&)
"could not find package harbour-barcode"
Jul 10 13:58:48 XperiaXZ2 [17585]: [D] unknown:0 - giving up
```

**Comment by keto** [comment]
What is the device model in `ssu s` output, and what Sailfish OS version is it runing?

**Comment by ApostolosB** [comment]
@keto 
Device model: Xperia XZ2 Compact (h8324 / h8324)
Release: 4.1.0.24

**Comment by monich** [comment]
Are you able to manually install rpms downloaded from [github](https://github.com/monich/sailfish-barcode/releases) or [openrepos](https://openrepos.net/content/slava/barcode)? That would rule out dependency issues.

**Comment by ApostolosB** [comment]
@monich it works from openrepos.

**Comment by ApostolosB** [comment]
Other people with officially supported devices seem to have issues also. 

https://forum.sailfishos.org/t/missing-apps-in-jolla-store/7404/8?u=apb

**Comment by ApostolosB** [comment]
Vige confirmed in the forum that it doesn't install because the 64bit version is not available in the store. I'll close this when it hits the store.

**Comment by monich** [comment]
> Vige confirmed in the forum that it doesn't install because the 64bit version is not available in the store. I'll close this when it hits the store.

Meaning that none of my other apps install too, right? Like Counter or Lines (simplest examples with minimal dependencies)

**Comment by ApostolosB** [comment]
@monich  haven't tried those sorry.

**Comment by monich** [comment]
> @monich haven't tried those sorry.

If they install, it would eliminate the 64-bit theory.

**Comment by ApostolosB** [comment]
Ok i tested. Counter doesn't install neither does Lines. So you probably need to make 64 bit versions or whatever.

**Comment by monich** [comment]
> Ok i tested. Counter doesn't install neither does Lines. So you probably need to make 64 bit versions or whatever.

So, to sum up. You have a 32-bit system and the store client doesn't pull a 32-bit rpm even though it's available, apparently because a matching 64-bit rpm (which you don't need) is missing. That's wrong. Uploading 64-bit rpm to Jolla Store bumps version requirements for 32-bit rpms to 4.0.1 which is also wrong - they are compatible with older versions of Sailfish OS.

Sounds like no matter what I do, something goes wrong. Then I choose to do nothing and keep it the way it is for the time being.

**Comment by ApostolosB** [comment]
I have a 64 bit system and i cant get the 64 bit version from the store. Which is missing. TBH i don't see a problem with bumping requirement on the official store. I think Jolla always recommends using the latest version of the OS on supported devices.

**Comment by monich** [comment]
Ah, ok. Then it's clear.

I have nothing against users upgrading their devices but if the package is 2.x or 3.x compatible it has to be marked as such. Otherwise the app will disappear from the store for the people still running 3.x even though the app is perfectly compatible with 3.x. Once that problem is fixed on the store side, I'll immediately upload 64-bit packages.

In the meantime, 64-bit builds would have to be downloaded from github or openrepos. Sorry about the inconvenience!

**Comment by ApostolosB** [comment]
@monich ping when the store situation gets sorted out.

**Comment by ApostolosB** [comment]
@monich  any updates to this?

**Comment by monich** [comment]
Unfortunately, at this point there seems to be more chances of Jolla Store apps getting further crippled by mandatory sandboxing than anything getting fixed. I'm sorry to say that but it appears to be rather unlikely that any 64-bit builds of my apps will ever appear in Jolla Store.

**Comment by poetaster** [comment]
Just to note, On 3.4 i can install Counter without problem. So that suggests:
1. App is available for 3.4/32bit
2. App is not available for 4.x/64 bit
3. App can still be installed.
That seems to assuage your fears from July 24?

**Comment by monich** [comment]
Actually, the versioning issue has suddenly been resolved (with the help of some pressure from the community, I heard), 64-bit package will soon appear in Jolla Store!

**Comment by poetaster** [comment]
cool. I've seen some other odd behaviour. I had posted armv7 and aarch64 and wasn't given the option to upload x86. This did NOT happen if I added x86 first. I haven't reported it yet. Need to do another test in store. sigh.

**Comment by ApostolosB** [comment]
Installed from the store and works. Closing.

Thanks for the resolution.
