### ISSUE TITLE
App pauses media player when scanning

### ISSUE THREAD

**Issue by ApostolosB** [monich/sailfish-barcode#33]
To rep:

1. Have media player playing an album (on BT headphones in case it matters). 
2. Open code reader and try to scan something
3. Music pauses.

It would be expected that the music continues to play.

**Comment by monich** [comment]
Yeah, camera behaves better, there's seems to be some room for improvement...

**Comment by monich** [comment]
I think version [1.0.46](https://github.com/monich/sailfish-barcode/releases/tag/v1.0.46) fixes the problem.
