### ISSUE TITLE
App crash click on button Contact Card

### ISSUE THREAD

**Issue by pherjung** [monich/sailfish-barcode#36]
Once BarCode recognized the QR-Code as VCARD, a button _Contact Card_ is available. Clicking on it make the application to stop.
Some log:
```
[D] unknown:0 - Using Wayland-EGL
library "libGLESv2_adreno.so" not found
library "eglSubDriverAndroid.so" not found
[D] onMustShowViewFinderChanged:205 - creating viewfinder ...
[D] onCameraActiveChanged:160 - camera has started
[W] unknown:0 - QConnmanTechnologyInterface::scanReply() "No carrier"
[D] onStatusChanged:219 - Page is INACTIVE
[D] destroyViewFinder:81 - destroying viewfinder ...
Terminated
```

**Comment by monich** [comment]
Does that happen with any contact card or a particular one?

**Comment by pherjung** [comment]
It happened with 2 different contacts. Here they are with anonymous data:
```
MECARD:N:Test  TestLastName;ORG:Test bla bla;TEL:+41 73 123 12 12;EMAIL:test.test@test.dd;TIL:Lorem Ipsum;;
```
And this one:
```
BEGIN:VCARD
VERSION:3.0
N:Mustername;Test;;;
FN:Test Mustername
NICKNAME:Test
TEL;TYPE=WORK;TYPE=PREF:+4161231212
TEL;TYPE=CELL:+41741231212
EMAIL;TYPE=PREF;TYPE=HOME:test@gmail.kk
EMAIL;TYPE=HOME:test@ha.kk
EMAIL;TYPE=WORK:test.test@test.gg
EMAIL;TYPE=HOME:test.test@gmail.com
X-SAMSUNGADR:;;70 Musterstrasse;Muster;;9008;Switzerland;Musterstrasse 70\nMuster 9008\nSwitzerland
ADR;TYPE=PREF;TYPE=HOME:;;70 Musterstrasse;Muster;;9008;Switzerland
URL:www.test.gg
BDAY:1979-07-29
END:VCARD
```

**Comment by monich** [comment]
Yes, I was able to reproduce the crash with a 64-bit build. It appears that any vcard crashes it. But strangely, 32-bit one works (and that's the one I was primarily using for debugging and development). I'll take a look.

**Comment by pherjung** [comment]
Oh my bad. I totally forgot to mention those important information. Sorry again.

**Comment by monich** [comment]
The app dies somewhere deep in the guts of Qt QML runtime trying to instantiate a system contact card viewer component.

Perhaps I should write a contact card viewer of my own. The one provided by the system won't be functional in a sandbox anyway. Not to mention it's never been intended to be used by 3-rd party apps.

**Comment by monich** [comment]
Release 1.0.48 replaces system contact UI with a builtin viewer. The crash should be gone now.
