### ISSUE TITLE
Read EAN-13

### ISSUE THREAD

**Issue by Aslanex** [monich/sailfish-barcode#6]
![2019-03-26 11 06 45](https://user-images.githubusercontent.com/4586137/54988726-5b3f5f00-4fb7-11e9-9837-d52d9a4275fa.jpg)

Could it be possible read a such code?

**Comment by monich** [comment]
It should be possible, and I have some EAN-13 codes in my scan history and I can scan random EAN-13 codes found by Google image search, but I have to admit that I can't read yours off the screen. It could be that it's just the image quality is not good enough...

**Comment by Aslanex** [comment]
com.google.zxing.client.android can read it instantly...

**Comment by monich** [comment]
I tried harder and was able to read it too!

![ean-13](https://user-images.githubusercontent.com/5909522/55114819-a3f83480-50eb-11e9-97ac-b2a6f02186c2.png)

(harbour-barcode-1.0.13 running on Sony Xperia XA2)

**Comment by monich** [comment]
I guess that answers the question :)
